import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

type Row = Record<string, any>;
function money(value: any) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value || 0)); }
function date(value: any) { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—"; }
const labels: Record<string, string> = { view: "Visualização", plan_selected: "Plano selecionado", configuration_changed: "Configuração alterada", comment: "Comentário", download_pdf: "Download de PDF", advance_intent: "Intenção de avanço", commercial_reply: "Resposta comercial" };
export function ProposalDetail({ proposal, client, onClose }: { proposal: Row; client: string; onClose: () => void }) {
  const [logs, setLogs] = useState<Row[]>([]); const [events, setEvents] = useState<Row[]>([]); const [lines, setLines] = useState<Row[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const db = supabase as any; Promise.all([db.from("proposal_access_log").select("id,success,attempted_at,user_agent").eq("proposal_id", proposal.id).order("attempted_at", { ascending: true }), db.from("proposal_interactions").select("id,actor,event_type,payload,created_at").eq("proposal_id", proposal.id).order("created_at", { ascending: false }), db.from("proposal_line_items").select("id,name,category,quantity,unit_price,periodicity,is_required,can_remove").eq("proposal_id", proposal.id).order("display_order")]).then(([access, interaction, items]) => { setLogs(access.data || []); setEvents(interaction.data || []); setLines(items.data || []); setLoading(false); }); }, [proposal.id]);
  const successful = logs.filter((log) => log.success); const first = successful[0]?.attempted_at; const last = successful[successful.length - 1]?.attempted_at; const response = (proposal as any).proposalResponse; const timeline = useMemo(() => [...events.map((event) => ({ ...event, kind: "event" })), ...logs.map((log) => ({ ...log, kind: "access", created_at: log.attempted_at }))].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()), [events, logs]);
  return <div style={overlay}><div style={panel}><header style={head}><div><div style={eyebrow}>Detalhe da proposta</div><h2 style={title}>{proposal.title || "Proposta youB"}</h2><p style={muted}>{client} · versão {proposal.version || 1}</p></div><button style={close} onClick={onClose}>×</button></header><main style={main}><div style={facts}><Fact label="Cliente" value={client} /><Fact label="Status" value={proposal.status || "rascunho"} /><Fact label="Valor" value={money(proposal.value)} /><Fact label="Validade" value={date(proposal.valid_until)} /><Fact label="Acessos válidos" value={String(successful.length)} /><Fact label="Primeiro acesso" value={date(first)} /><Fact label="Último acesso" value={date(last)} /><Fact label="Link" value={proposal.public_token ? `${window.location.origin}/p/${proposal.public_token}` : "—"} /></div>{response && <section style={card}><h3 style={sectionTitle}>Devolutiva mais recente</h3><p><strong>Plano:</strong> {response.selected_plan || "Não informado"}</p>{response.comment && <p><strong>Comentário:</strong> {response.comment}</p>}</section>}<section style={card}><h3 style={sectionTitle}>Configuração da versão</h3>{lines.length ? <div>{lines.map((line) => <div key={line.id} style={lineRow}><div><strong>{line.name}</strong><small>{line.category} · {line.quantity} {line.periodicity} · {line.is_required ? "obrigatório" : line.can_remove ? "opcional" : "não removível"}</small></div><strong>{money(Number(line.quantity) * Number(line.unit_price))}</strong></div>)}</div> : <p style={muted}>Nenhum item registrado nesta versão.</p>}</section><section style={card}><h3 style={sectionTitle}>Histórico</h3>{loading ? <p style={muted}>Carregando histórico…</p> : timeline.length ? <div>{timeline.map((item) => <div key={`${item.kind}-${item.id}`} style={historyRow}><span style={{ ...dot, background: item.kind === "access" ? (item.success ? "#22c55e" : "#ef4444") : "#7c3aed" }} /><div><strong>{item.kind === "access" ? (item.success ? "Acesso liberado" : "Tentativa de acesso") : labels[item.event_type] || item.event_type}</strong><small>{date(item.created_at)}{item.kind === "event" && item.payload?.selectedPlan ? ` · ${item.payload.selectedPlan}` : ""}</small>{item.kind === "event" && item.payload?.comment && <p>{item.payload.comment}</p>}</div></div>)}</div> : <p style={muted}>Nenhuma interação registrada ainda.</p>}</section></main></div></div>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div style={fact}><span>{label}</span><strong>{value}</strong></div>; }
const overlay: React.CSSProperties = { position: "fixed", inset: 0, zIndex: 70, background: "#29143e66", display: "grid", placeItems: "center", padding: 20 }; const panel: React.CSSProperties = { width: "min(980px,100%)", maxHeight: "92vh", overflow: "auto", background: "#f8f7fb", borderRadius: 18, boxShadow: "0 30px 80px #16091f55" }; const head: React.CSSProperties = { padding: "24px 30px", display: "flex", justifyContent: "space-between", gap: 20, background: "#fff", borderBottom: "1px solid #eeeaf2" }; const eyebrow: React.CSSProperties = { color: "#7c3aed", textTransform: "uppercase", letterSpacing: 1.2, fontSize: 10, fontWeight: 850 }; const title: React.CSSProperties = { margin: "6px 0", color: "#29143e" }; const muted: React.CSSProperties = { color: "#83798b", fontSize: 12, lineHeight: 1.5 }; const close: React.CSSProperties = { border: 0, background: "transparent", fontSize: 28, color: "#8b8194", cursor: "pointer" }; const main: React.CSSProperties = { padding: 24, display: "grid", gap: 16 }; const facts: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", gap: 10 }; const fact: React.CSSProperties = { padding: "14px 16px", borderRadius: 12, background: "#fff", border: "1px solid #eceaf2", display: "flex", flexDirection: "column", gap: 6 }; const card: React.CSSProperties = { padding: "18px 20px", borderRadius: 14, background: "#fff", border: "1px solid #eceaf2" }; const sectionTitle: React.CSSProperties = { margin: "0 0 15px", color: "#32134f", fontSize: 15 }; const lineRow: React.CSSProperties = { display: "flex", justifyContent: "space-between", gap: 16, padding: "12px 0", borderBottom: "1px solid #f0edf5" }; const historyRow: React.CSSProperties = { display: "flex", gap: 12, padding: "11px 0", borderBottom: "1px solid #f0edf5" }; const dot: React.CSSProperties = { width: 9, height: 9, borderRadius: "50%", marginTop: 5, flex: "0 0 auto" };
